name: publish
on: [workflow_dispatch, repository_dispatch]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          date > published.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Published Changes"
          git push